<?php

return [
    'groups' => [
        'company' => 'Company Identity',
        'sso' => 'SSO',
        'iam' => 'IAM',
        'auth' => 'Authentication',
        'fortify' => 'Fortify',
        'ui' => 'User Interface',
    ],

    'definitions' => [
        'company.name' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'RS Citra Husada Sejahtera',
            'description' => 'Nama resmi perusahaan / instansi',
            'source' => 'company identity',
        ],

        'company.tagline' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'Melayani dengan Hati dan Profesionalisme',
            'description' => 'Tagline atau slogan perusahaan',
            'source' => 'company identity',
        ],

        'company.logo' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'text',
            'default' => '/images/company/logo.png',
            'description' => 'URL logo perusahaan (digunakan untuk dokumen & UI)',
            'source' => 'company identity',
        ],

        'company.address' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'textarea',
            'default' => 'Jl. Raya Kesehatan No. 123, Kecamatan Sejahtera',
            'description' => 'Alamat lengkap perusahaan',
            'source' => 'company identity',
        ],

        'company.phone' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'text',
            'default' => '(0331) 123456',
            'description' => 'Nomor telepon utama',
            'source' => 'company identity',
        ],

        'company.email' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'email',
            'default' => 'info@citrahusada.co.id',
            'description' => 'Email resmi perusahaan',
            'source' => 'company identity',
        ],

        'company.website' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'url',
            'default' => 'https://citrahusada.co.id',
            'description' => 'Website resmi perusahaan',
            'source' => 'company identity',
        ],

        'company.city' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'Jember',
            'description' => 'Kota lokasi perusahaan (untuk dokumen)',
            'source' => 'company identity',
        ],

        'company.postal_code' => [
            'group' => 'company',
            'type' => 'string',
            'input_type' => 'text',
            'default' => '68121',
            'description' => 'Kode pos perusahaan',
            'source' => 'company identity',
        ],

        'sso.issuer' => [
            'group' => 'sso',
            'type' => 'string',
            'input_type' => 'text',
            'default' => env('SSO_ISSUER', env('APP_URL', 'iam-server')),
            'description' => 'Identifies the IAM server in issued tokens',
            'source' => 'config/sso.php:issuer',
        ],
        'sso.secret' => [
            'group' => 'sso',
            'type' => 'string',
            'input_type' => 'password',
            'default' => env('SSO_SECRET', env('APP_KEY')),
            'description' => 'HMAC secret used to sign and verify internal SSO tokens',
            'source' => 'config/sso.php:secret',
            'is_sensitive' => true,
        ],
        'sso.ttl' => [
            'group' => 'sso',
            'type' => 'integer',
            'input_type' => 'number',
            'default' => (int) env('SSO_TTL', 300),
            'description' => 'The lifetime in seconds for issued SSO tokens',
            'source' => 'config/sso.php:ttl',
        ],
        'sso.backchannel.signature_header' => [
            'group' => 'sso',
            'type' => 'string',
            'input_type' => 'text',
            'default' => env('SSO_BACKCHANNEL_SIGNATURE_HEADER', 'IAM-Signature'),
            'description' => 'Shared configuration value for SSO token verification',
            'source' => 'config/sso.php:backchannel.signature_header',
        ],

        'iam.home_app' => [
            'group' => 'iam',
            'type' => 'json',
            'input_type' => 'json',
            'default' => [
                'enabled' => env('IAM_HOME_APP_ENABLED', true),
                'app_key' => env('IAM_HOME_APP_KEY', 'iam-home'),
                'name' => env('IAM_HOME_APP_NAME', 'IAM Home'),
                'description' => env('IAM_HOME_APP_DESCRIPTION', 'Portal utama IAM'),
                'url' => env('IAM_HOME_URL', 'http://127.0.0.1:8010/'),
                'logo_url' => env('IAM_HOME_APP_LOGO_URL', null),
            ],
            'description' => 'Default app entry injected in user applications response',
            'source' => 'config/iam.php:home_app',
        ],
        'iam.app_key' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'text',
            'default' => null,
            'description' => 'Optional app key restriction for access token verification',
            'source' => 'app/Http/Middleware/VerifyIAMAccessToken.php',
        ],
        'iam.issuer' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'text',
            'default' => env('IAM_ISSUER', env('APP_URL', 'https://iam.local')),
            'description' => 'Issuer identifier for JWT tokens',
            'source' => 'config/iam.php:issuer',
        ],
        'iam.token_ttl' => [
            'group' => 'iam',
            'type' => 'integer',
            'input_type' => 'number',
            'default' => (int) env('IAM_TOKEN_TTL', 3600),
            'description' => 'Default lifetime in seconds for access tokens issued by IAM',
            'source' => 'config/iam.php:token_ttl',
        ],
        'iam.unit_kerja_delete_soft' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_UNIT_KERJA_DELETE_SOFT', false),
            'description' => 'Control how deleted unit kerja are handled',
            'source' => 'config/iam.php:unit_kerja_delete_soft',
        ],
        'iam.user_delete_soft' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_USER_DELETE_SOFT', false),
            'description' => 'Control how deleted users are handled',
            'source' => 'config/iam.php:user_delete_soft',
        ],
        'iam.push_deleted_records' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_PUSH_DELETED_RECORDS', true),
            'description' => 'Include deleted records in push payload',
            'source' => 'config/iam.php:push_deleted_records',
        ],
        'iam.sso_secret' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'password',
            'default' => env('IAM_SSO_SECRET', env('SSO_SECRET', env('IAM_JWT_SECRET'))),
            'description' => 'Shared secret used for backchannel HMAC verification with client apps',
            'source' => 'config/iam.php:sso_secret',
            'is_sensitive' => true,
        ],
        'iam.jwt_secret' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'password',
            'default' => env('IAM_JWT_SECRET', env('APP_KEY')),
            'description' => 'Secret key used to sign JWT tokens',
            'source' => 'config/iam.php:jwt_secret',
            'is_sensitive' => true,
        ],
        'iam.signing_key' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'password',
            'default' => env('IAM_SIGNING_KEY', env('IAM_JWT_SECRET')),
            'description' => 'Secret key used to sign JWT tokens',
            'source' => 'config/iam.php:signing_key',
            'is_sensitive' => true,
        ],
        'iam.backchannel_verify' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_BACKCHANNEL_VERIFY', true),
            'description' => 'Whether to enforce backchannel verification',
            'source' => 'config/iam.php:backchannel_verify',
        ],
        'iam.backchannel_method' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'select',
            'select_options' => ['jwt', 'hmac'],
            'default' => env('IAM_BACKCHANNEL_METHOD', 'jwt'),
            'description' => 'Mechanism used for server-to-server requests',
            'source' => 'config/iam.php:backchannel_method',
        ],
        'iam.algorithm' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'text',
            'default' => env('IAM_JWT_ALGORITHM', 'HS256'),
            'description' => 'JWT algorithm used to sign tokens',
            'source' => 'config/iam.php:algorithm',
        ],
        'iam.refresh_token_ttl' => [
            'group' => 'iam',
            'type' => 'integer',
            'input_type' => 'number',
            'default' => (int) env('IAM_REFRESH_TOKEN_TTL', 86400 * 30),
            'description' => 'Lifetime in seconds for refresh tokens',
            'source' => 'config/iam.php:refresh_token_ttl',
        ],
        'iam.auth_code_ttl' => [
            'group' => 'iam',
            'type' => 'integer',
            'input_type' => 'number',
            'default' => (int) env('IAM_AUTH_CODE_TTL', 300),
            'description' => 'Lifetime in seconds for authorization codes',
            'source' => 'config/iam.php:auth_code_ttl',
        ],
        'iam.audience' => [
            'group' => 'iam',
            'type' => 'json',
            'input_type' => 'json',
            'default' => null,
            'description' => 'Optional audience claim for JWT tokens',
            'source' => 'config/iam.php:audience',
        ],
        'iam.protect_system_roles' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_PROTECT_SYSTEM_ROLES', true),
            'description' => 'Whether to enforce protection on system roles',
            'source' => 'config/iam.php:protect_system_roles',
        ],
        'iam.user_sync_mode' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'select',
            'select_options' => ['pull', 'push'],
            'default' => env('IAM_USER_SYNC_MODE', 'push'),
            'description' => 'Direction of user sync between IAM and client',
            'source' => 'config/iam.php:user_sync_mode',
        ],
        'iam.role_sync_mode' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'select',
            'select_options' => ['pull', 'push'],
            'default' => env('IAM_ROLE_SYNC_MODE', 'push'),
            'description' => 'Direction of role sync between IAM and client',
            'source' => 'config/iam.php:role_sync_mode',
        ],
        'iam.role_sync_from_client_allow_create' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_ROLE_SYNC_FROM_CLIENT_ALLOW_CREATE', false),
            'description' => 'If true, IAM creates roles that exist in client but not in IAM',
            'source' => 'config/iam.php:role_sync_from_client_allow_create',
        ],
        'iam.role_sync_from_iam_allow_create' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_ROLE_SYNC_FROM_IAM_ALLOW_CREATE', false),
            'description' => 'In push mode, allow clients to create new roles from IAM payload',
            'source' => 'config/iam.php:role_sync_from_iam_allow_create',
        ],
        'iam.user_sync_from_iam_allow_create' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_USER_SYNC_FROM_IAM_ALLOW_CREATE', true),
            'description' => 'When push mode is active, allow IAM to create new users',
            'source' => 'config/iam.php:user_sync_from_iam_allow_create',
        ],
        'iam.user_sync_from_iam_delete_missing' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_USER_SYNC_FROM_IAM_DELETE_MISSING', false),
            'description' => 'When pushing users, allow clients to delete/disable missing users',
            'source' => 'config/iam.php:user_sync_from_iam_delete_missing',
        ],
        'iam.user_sync_force_pull' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_USER_SYNC_FORCE_PULL', false),
            'description' => 'Force user sync to pull values from client even if push mode is available',
            'source' => 'config/iam.php:user_sync_force_pull',
        ],
        'iam.user_sync_password_field' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => (bool) env('IAM_USER_SYNC_PASSWORD_FIELD', false),
            'description' => 'Whether user sync should include password field',
            'source' => 'config/iam.php:user_sync_password_field',
        ],
        'iam.user_fields' => [
            'group' => 'iam',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'id,name,nip,email,status',
            'description' => 'Comma-separated user fields included in API responses',
            'source' => 'config/iam.php:user_fields',
        ],
        'iam.sync_unit_kerja' => [
            'group' => 'iam',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => true,
            'description' => 'Control whether Unit Kerja CRUD is allowed',
            'source' => 'app/Filament/Panel/Resources/UnitKerjas/UnitKerjaResource.php',
        ],
        'iam.default_user_roles' => [
            'group' => 'iam',
            'type' => 'json',
            'input_type' => 'json',
            'default' => [],
            'description' => 'Optional default roles assigned to new users per application',
            'source' => 'config/iam.php:default_user_roles',
        ],
        'iam.imports' => [
            'group' => 'iam',
            'type' => 'json',
            'input_type' => 'json',
            'default' => [
                'delete_source_after_import' => (bool) env('IAM_IMPORT_DELETE_SOURCE_AFTER_IMPORT', false),
            ],
            'description' => 'Controls for JSON import jobs',
            'source' => 'app/Jobs/ImportUnitKerjasFromJsonJob.php',
        ],

        'auth.defaults.guard' => [
            'group' => 'auth',
            'type' => 'string',
            'input_type' => 'select',
            'select_options' => ['web', 'api'],
            'default' => env('AUTH_GUARD', 'web'),
            'description' => 'Default authentication guard',
            'source' => 'config/auth.php:defaults.guard',
        ],
        'auth.defaults.passwords' => [
            'group' => 'auth',
            'type' => 'string',
            'input_type' => 'text',
            'default' => env('AUTH_PASSWORD_BROKER', 'users'),
            'description' => 'Default password broker',
            'source' => 'config/auth.php:defaults.passwords',
        ],

        'fortify.guard' => [
            'group' => 'fortify',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'web',
            'description' => 'Fortify guard',
            'source' => 'config/fortify.php:guard',
        ],
        'fortify.passwords' => [
            'group' => 'fortify',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'users',
            'description' => 'Fortify password broker',
            'source' => 'config/fortify.php:passwords',
        ],
        'fortify.username' => [
            'group' => 'fortify',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'nip',
            'description' => 'Username field used by Fortify',
            'source' => 'config/fortify.php:username',
        ],
        'fortify.email' => [
            'group' => 'fortify',
            'type' => 'string',
            'input_type' => 'text',
            'default' => 'nip',
            'description' => 'Email field used by Fortify',
            'source' => 'config/fortify.php:email',
        ],
        'fortify.lowercase_usernames' => [
            'group' => 'fortify',
            'type' => 'boolean',
            'input_type' => 'toggle',
            'default' => true,
            'description' => 'Whether usernames should be lowercased',
            'source' => 'config/fortify.php:lowercase_usernames',
        ],
        'login_view' => [
            'group' => 'ui',
            'type' => 'string',
            'input_type' => 'select',
            'select_options' => ['default', 'type1'],
            'default' => 'type1',
            'description' => 'Select which login page variant to load',
            'source' => 'resources/js/components/Login.tsx',
        ],
        'fortify.home' => [
            'group' => 'fortify',
            'type' => 'string',
            'input_type' => 'text',
            'default' => '/dashboard',
            'description' => 'Redirect path after successful authentication',
            'source' => 'config/fortify.php:home',
        ],
    ],
];
